on: [push]

jobs:
  kernel:
    runs-on: ubuntu-latest
    name: build kernel
    steps:
      - uses: AaronJackson/2.11BSD-Action@rsyncfix
        with:
          path: /usr/src
          patch_level: 477
          run: |
            cd /usr/src/sys/conf
            ./config GENERIC
            cd ../GENERIC
            make
            cd /usr/src/bin
            make
            cd /usr/src/sbin
            make
            cd /usr/src/usr.bin/f77
            rm -f malloc.c
            make
            cd /usr/src/bin
            make df size
            cd /usr/src/ucb/top
            make
            cd /usr/src/bin/disklabel
            make clean
            make
            cd /usr/src/sys/mdec
            make clean
            make
