on: [push]

jobs:
  kernel:
    runs-on: ubuntu-latest
    name: build kernel
    steps:
      - uses: AaronJackson/2.11BSD-Action@v1.0
        with:
          path: /usr/src
          run: |
            cd sys/conf
            ./config GENERIC
            cd ../GENERIC
            make

  bin:
    runs-on: ubuntu-latest
    name: build /bin
    steps:
      - uses: AaronJackson/2.11BSD-Action@v1.0
        with:
          path: /usr/src
          run: |
            cd bin
            make

  sbin:
    runs-on: ubuntu-latest
    name: build /sbin
    steps:
      - uses: AaronJackson/2.11BSD-Action@v1.0
        with:
          path: /usr/src
          run: |
            cd sbin
            make

  usr_bin:
    runs-on: ubuntu-latest
    name: build /usr/bin
    steps:
      - uses: AaronJackson/2.11BSD-Action@v1.0
        with:
          path: /usr/src
          run: |
            cd usr.bin
            make


  usr_sbin:
    runs-on: ubuntu-latest
    name: build /usr/sbin
    steps:
      - uses: AaronJackson/2.11BSD-Action@v1.0
        with:
          path: /usr/src
          run: |
            cd usr.sbin
            make
