on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build 2.11BSD kernel
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use 2.11BSD container
        run: |
          docker run -v /$GITHUB_WORKSPACE:/github --device /dev/fuse \
                     --cap-add SYS_ADMIN asjackson/2.11bsd-ci:latest
