on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run some builds
    steps:
      - name: Build kernel
        uses: AaronJackson/2.11BSD-Action@v1.0
        with:
          path: /usr/src
          run: |
            cd sys/conf
            ./config GENERIC
            cd ../GENERIC
            make
