on: [push]

jobs:
  kernel:
    runs-on: ubuntu-latest
    name: build kernel
    steps:
      - uses: AaronJackson/2.11BSD-Action@main
        with:
          path: /usr/src
          patch_level: 459
          run: |
            cd /usr/src/sys/conf
            ./config GENERIC
            cd ../GENERIC
            make
            cd /usr/src/bin
            make
            cd /usr/src/sbin
            make
