on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build 2.11BSD kernel
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use 2.11BSD container
        run: |
          docker network create --driver=bridge --subnet=10.0.2.0/24 br0
          docker run -v /$GITHUB_WORKSPACE:/github --network=br0 --ip=10.0.2.100 asjackson/2.11bsd-ci:v0.8
