on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build 2.11BSD kernel
    steps:
      - name: Checkout
        uses: AaronJackson/2.11BSD-Action
        with:
          path: /usr/src/sys
          run: |
            cd GENERIC
            make
